spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm:
  admin-user:
    id: uadmin
    password: padmin
  deployment-resource-pattern: classpath*:**/*.bpmn, classpath*:**/*.bpmn20.xml, classpath*:**/*.dmn, classpath*:**/*.dmn11.xml, classpath*:**/*.cmmn, classpath*:**/*.cmmn10.xml, classpath*:**/*.cmmn11.xml, classpath*:**/*.form